#!/bin/bash

# ssh disable password authentication
sed -i 's/^PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
systemctl restart sshd.service

# Time zone
/bin/cp -p /usr/share/zoneinfo/Japan /etc/localtime
echo 'ZONE="Asia/Tokyo"' > /etc/sysconfig/clock
echo 'UTC=false' >> /etc/sysconfig/clock

# Yum
## Utility
yum install -y \
    bash-completion \
    bind-utils \
    lsof \
    net-tools \
    screen \
    sos \
    sysstat
## Editor
yum install -y \
    vim-enhanced

